### ISSUE TITLE
Unpublished products

### ISSUE THREAD

**Issue by mkjackson83** [labd/commercetools-node-mock#51]
Hi,

It seems as if currently the library doesn't support mocking of unpublished products, when fetching via a product projection search.
https://github.com/labd/commercetools-node-mock/blob/536b2dec9aef3d8523223bcf967952b45fbb5442/src/product-projection-search.ts#L150-L167

Please could this be added?

Best regards

**Comment by mvantellingen** [comment]
Yes this seems to be not implemented yet correctly. See WIP branch https://github.com/labd/commercetools-node-mock/pull/53

**Comment by mvantellingen** [comment]
Should be fixed in 0.10.0, could you give that at try?

**Comment by mkjackson83** [comment]
Thanks very much Michael.  I don't have time to do it immediately, but hopefully will get chance in the coming days

**Comment by mikedebock** [comment]
@mvantellingen / @mkjackson83 I can confirm that this issue is now resolved.
