### ISSUE TITLE
Is standalone price supported? Error Request returned status code 404

### ISSUE THREAD

**Issue by Atul-Bari** [labd/commercetools-node-mock#61]
Hi,

I am trying to write mock tests for creating and reading standalone prices in the commerce tool.

Created client as->
ENV:
CTP_PROJECT_KEY=unittest
CTP_API_URL=http://localhost:8989
CTP_AUTH_URL=http://localhost:8989/oauth/token
PRICING_CT_CLIENT_ID=unittest
PRICING_CT_CLIENT_SECRET=unittest
CTP_SCOPES=manage_project:todo

Error:
Trying to get or set standalone price but getting error as **Request returned status code 404**
`POST /oauth/token 200 100 - 63.845 ms`
`GET /unittest/standalone-prices?expand=channel&limit=500&offset=0&sort=lastModifiedAt+asc 404 165 - 23.144 ms`
`POST /oauth/token 200 100 - 13.803 ms`
`POST /unittest/standalone-prices 404 166 - 49.026 ms`

Should I include anything here?

**Comment by mvantellingen** [comment]
Just released the latest version with the #62 merged which adds this
