### ISSUE TITLE
devDependencies and peerDependencies for @commercetools/platform-sdk

### ISSUE THREAD

**Issue by lorenzosfarra** [labd/commercetools-node-mock#82]
Hi,

I am a very happy user of this library, thank you for it!

Right now I have to update `@commercetools/platform-sdk` (2.X --> 4.X) and `@commercetools/sdk-client-v2` (1.C --> 2.X) in my project, but I am having conflicts regarding this library.

In fact, in the v1.2 *package.json* of this library  the `@commercetools/platform-sdk` package is listed in both devDependencies and peerDependencies, but with different versions:

```
  "devDependencies": {
    ...
    "@commercetools/platform-sdk": "4.0.0",
    ...
  },
  "peerDependencies": {
    "@commercetools/platform-sdk": "^2.4.1"
  }
```

As per my understanding, devDependencies should contain packages that are required during development, while peerDependencies should declare compatibility requirements with other packages. Having the same package with different versions in these sections seems unusual and might lead to conflicts during the dependency resolution process.

I wanted to reach out to you and inquire if there is a specific reason for this version discrepancy. Is it intentional, or is there a compatibility consideration that I might be missing?

Thanks,
   Lorenzo

**Comment by mvantellingen** [comment]
I think this was fixed some releases ago. thanks for the report though 👍
